name: Test & Commit

on:
  push:
    branches:
      - main

jobs:
  test_commit:
    runs-on: macos-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Environment
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0.0

    - name: Install Gems
      run: |
          bundle install

    - name: Run Tests
      run: |
        rubocop
        rspec

    - name: Commit Changes
      run:

    - name: Push Commit
      run:
