name: Test & Commit

on:
  push:
    branches:
      - actions-test

jobs:
  test_commit:
    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Environment
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0.0

    # - name: Install Gems
    #   run: |
    #       bundle install
    #
    # - name: Run Tests
    #   run: |
    #     rubocop
    #     rspec

    - name: Commit If Changes
      if: ${{ git diff -q }}
      run: echo "Commit required."
        # git config user.name "GitHub Action"
        # git config user.email "github-actions@github.com"
