name: RSpec Test, Commit & Push

on: [push]

jobs:
  RSpec_Tests:
    runs-on: macos-latest

    steps:

    - name: Set up environment
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0.0

    - name: Install and update gems
      run: |
          bundle install
          bundle update

    - run: rspec

    # - name: Commit and push commit
    #   run: |
    #       git config user.name github-actions
    #       git config user.email github-actions@github.com
    #       git add .
    #       git commit -m "GitHub Action commit."
    #       git push
