name: SimpleCov_Shield_Badge

on: [push]

jobs:
  RSpec Tests:
    runs-on: macos-latest

    env:
      RUBY_VERSION: 3.0.0
      GITHUB_USER: "JoshSinyor"
      GITHUB_MAIL: ${{ secrets.MAIL }}
      GITHUB_ORG: "JoshSinyor"
      GITHUB_REPO: "bank_tech_test"
      GITHUB_ACCESS_TOKEN: ${{ secrets.TOKEN }}

    steps:
    - uses: actions/checkout@v1
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0.0
    - run: bundle install
    - run: rspec
